# Generated by Django 3.1.6 on 2021-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_profile_wallet_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
