# Generated by Django 3.1.6 on 2021-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210730_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='gbvariables',
            fields=[
                ('gb_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_allowed_registerUser', models.IntegerField(default=3)),
                ('no_of_allowed_addDevice', models.IntegerField(default=3)),
            ],
        ),
    ]
