# Generated by Django 4.1 on 2022-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_user_profile_is_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_address',
            field=models.CharField(default='cv', max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_city',
            field=models.CharField(default='cv', max_length=40),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_country',
            field=models.CharField(default='cv', max_length=50),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_pincode',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_state',
            field=models.CharField(default='cv', max_length=40),
        ),
    ]
