# Generated by Django 3.2.4 on 2021-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dustbin',
            name='dustbin_level',
        ),
        migrations.RemoveField(
            model_name='waterpoint',
            name='water_level',
        ),
        migrations.AddField(
            model_name='dustbin',
            name='bin_avai_volume',
            field=models.FloatField(default='20'),
        ),
        migrations.AddField(
            model_name='dustbin',
            name='bin_init_height',
            field=models.FloatField(default='20'),
        ),
        migrations.AddField(
            model_name='dustbin',
            name='bin_init_volume',
            field=models.FloatField(default='20'),
        ),
        migrations.AddField(
            model_name='waterpoint',
            name='total_water_capacity',
            field=models.FloatField(default='20'),
        ),
        migrations.AddField(
            model_name='waterpoint',
            name='water_available',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_mac',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
