# Generated by Django 3.1.6 on 2021-07-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210727_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dustbin',
            old_name='bin_init_height',
            new_name='bin_total_height',
        ),
        migrations.RenameField(
            model_name='dustbin',
            old_name='bin_init_volume',
            new_name='bin_total_volume',
        ),
    ]
