# Generated by Django 3.1.6 on 2021-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_smarttoilet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarttoilet',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='smarttoilet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
